Add argument to be able to specify manifest name
personalrobotics/pr-cleanroom pull request #13
Opened 2018-04-12 23:55 UTC by jslee02

2018-04-13 17:07 UTC, aditya-vk approved these changes
LGTM!

2018-04-13 17:51 UTC, brianhou requested changes

2018-04-13 17:51 UTC, brianhou commented on internal-distro.py
> +    parser.add_argument('--manifest_file', type=str, default='package.xml')
Nit: Can we make this `--manifest-file` instead? This doesn't change the code below (it'd still be `args.manifest_file`).

2018-04-13 18:30 UTC, brianhou commented
I thought about this a bit more, and it seems that our options are either to:

- Have multiple `package.xml` files in each Catkin package. The versions that are used are either (1) all named `package.xml` (current behavior) or (2) `args.manifest_file` if that file exists and `package.xml` if it doesn't (behavior introduced in this PR).
- Have one `package.xml` file in each Catkin package and programmatically generate other ones (e.g. `package-full.xml`) depending on `args.manifest_file`.

I think one potential drawback to the first option that we've implemented here is that two (or multiple?) `package.xml` files could get out of sync. If we were to generate the full `package.xml` by (programmatically) commenting out the appropriate sections in `package.xml`, I feel like this wouldn't be a problem.

One potential drawback of the second option is that we get a bit farther away from the "standard" `package.xml` description. From a quick skim of their code, the Catkin package parser is quite strict about unknown XML tags, so we'd have to continue embedding these optional dependencies as comments.

What do you think? I can help implement the second option if you think it sounds beneficial.

2018-04-13 22:58 UTC, jslee02 commented
The second option sounds good to me. As Catkin package parser wouldn't be happy with introducing unknown XML tags, we might need to parse comments in a specific format we make.

If you implement the second option, I would happy to close this PR. :smile:

2018-04-17 23:04 UTC, jslee02 commented
Thanks for the review @aditya-vk and @brianhou. Closing this PR in favor of https://github.com/personalrobotics/pr-cleanroom/pull/14 though.

2018-04-17 23:04 UTC, closed without merging

2018-04-18 01:42 UTC, mkoval commented
I think we should revert https://github.com/personalrobotics/aikido/pull/364 and fix https://github.com/personalrobotics/pr-rosinstalls/pull/36 by forcing everyone to install the dependencies required to run on real hardware. This is a draconian solution, but I think it is the best option given Catkin's limitations.

I don't see any value in encoding optional dependencies in the `package.xml` file using a custom tag, since no Catkin tools know what to do with them. This means that: (1) `rosdep` will not install those dependencies, which breaks our installation instructions, and (2) `catkin build` may build the packages out-of-order, e.g. by starting to build a package before all of its dependencies are built.

---

Note that if we do decide to use a custom tag for optional dependencies, we should use the [`<export>` tag](http://www.ros.org/reps/rep-0140.html#export) in `package.xml`. It is intended for exactly this use-case.

2018-04-18 16:23 UTC, jslee02 commented
This solution was to solve this issue https://github.com/personalrobotics/pr-rosinstalls/pull/36; we sometimes want to build AIKIDO with the minimal dependencies only for simulation. I think this is why we introduced the component build system to AIKIDO.

If we don't want any optional build with Catkin, then we could just use pure CMake without Catkin. In this case, we should accept https://github.com/personalrobotics/pr-rosinstalls/pull/36. But we just try to find a resonable workaround with Catkin.

I see your concerns with a custom tag. How about we go with the opposite way? By default, `package.xml` contains all the depedencies so that it generally works for normal Catkin builds. And then, if we want minimal AIKIDO build (w/ `herb-minimal-sim.rosinstall` for example), we manually comment out the optional dependencies. In CI, we will use `internal-distro.py` to automate the work reading the custom tag or using `<export>` tag.